name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: 9.0.x
  CONFIGURATION: Release

jobs:
  build-test:    
    runs-on: ubuntu-latest   
    name: Build and test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Restore
      shell: bash
      run: dotnet restore --locked-mode

    - name: Build
      shell: bash
      run: dotnet build -c ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      shell: bash
      run: dotnet test -c ${{ env.CONFIGURATION }} --no-build

  codeql-analysis:    
    name: CodeQL analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
        
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dependency-review:
    if: ${{ github.event_name == 'pull_request' }}
    name: Dependency review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency review
        uses: actions/dependency-review-action@v4